Byteland\DomainBundle\Entity\AvailableRestaurant:
  type: entity
  table: available_restaurant
  id:
      id:
        column: available_restaurant_id
        type: integer
        generator: { strategy: AUTO }
        options:
          unsigned: true
  manyToOne:
    reserveList:
      targetEntity: ReserveList
      inversedBy: availableRestaurants
      joinColumn:
        name: reserve_list_id
        referencedColumnName: reserve_list_id
  oneToOne:
      restaurant:
        targetEntity: Restaurant
        cascade: ["persist"]
        joinColumn:
          name: restaurant_id
          referencedColumnName: restaurant_id