Byteland\DomainBundle\Entity\Client:
  type: entity
  table: client
  id:
    id:
      column: client_id
      type: integer
      generator: { strategy: AUTO }
      options:
        unsigned: true
  fields:
    name:
      type: string
      length: 45