Byteland\DomainBundle\Entity\ReserveList:
  type: entity
  table: reserve_list
  id:
      id:
        column: reserve_list_id
        type: integer
        generator: { strategy: AUTO }
        options:
          unsigned: true
  fields:
    date:
        type: date
        column: date
  oneToMany:
      availableRestaurants:
        targetEntity: AvailableRestaurant
        mappedBy: reserveList
        indexBy: id