Byteland\DomainBundle\Entity\Restaurant:
  type: entity
  table: restaurant
  id:
    id:
      column: restaurant_id
      type: integer
      generator: { strategy: AUTO }
      options:
        unsigned: true
  fields:
    name:
      type: string
      length: 100
    capacity:
      type: integer
      options:
        unsigned: true